server:
  port: 8081
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: tomcat
    key-store-type: PKCS12
    key-alias: tomcat

zuul:
  routes:
    resource:
      path: /api/**
      url: https://localhost:8443/
      sensitiveHeaders:
      strip-prefix: false
    login:
      path: /login
      url: https://localhost:8443/
      sensitiveHeaders:
      strip-prefix: false
    oath:
      path: /oauth/**
      url: https://localhost:8443/
    assets:
      path: /assets/**
      url: https://localhost:8443/
      # needed for all headers to be forwarded both in request & response
      sensitiveHeaders:
      strip-prefix: false
  # needed for self-signed certificates to work.
  ssl-hostname-validation-enabled: false
  # fix the url returned inside HATEOAS links (otherwise it's: ..../api/api/....)
  add-proxy-headers: false
  include-debug-header: true
logging:
  level:
    org:
      springframework: debug
eureka:
  client:
    enabled: false
security:
  basic:
    enabled: false
    # TODO blocking issue with zuul:
    # https://github.com/spring-cloud/spring-cloud-netflix/issues/1295
    # we cannot disable zuul from following redirects
ribbon:
  FollowRedirects: false
