#server:
#  port: 8081
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: tomcat
#    key-store-type: PKCS12
#    key-alias: tomcat

zuul:
  routes:
    resource:
      path: /api/**
      serviceId: spring-boot-startup
      sensitiveHeaders:
      strip-prefix: false
    login:
      path: /login
      serviceId: spring-boot-startup
      sensitiveHeaders:
      strip-prefix: false
    oath:
      path: /oauth/**
      serviceId: spring-boot-startup
      # needed for all headers to be forwarded both in request & response
      sensitiveHeaders:
      strip-prefix: false
  # needed for self-signed certificates to work. due to a bug true must be passed to the flag instead of false...
  ssl-hostname-validation-enabled: true
  # fix the url returned inside HATEOAS links (otherwise it's: ..../api/api/....)
  add-proxy-headers: false

logging:
  level:
    org:
      springframework: debug
spring:
  application:
    name: experiment-primeng
security:
  basic:
    enabled: false
eureka:
  client:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ConnectTimeout: 120000
  ReadTimeout: 120000
