server:
  port: 8081
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: tomcat
    key-store-type: PKCS12
    key-alias: tomcat

zuul:
  routes:
    resource:
      path: /api/**
      url: https://localhost:8080/api
      sensitiveHeaders:
    login:
      path: /login
      url: https://localhost:8080/
      sensitiveHeaders:
logging:
  level:
    org:
      springframework: debug
