server:
  port: 8081
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: tomcat
    key-store-type: PKCS12
    key-alias: tomcat

zuul:
  routes:
    resource:
      path: /api/**
      url: https://localhost:8080/api
      sensitiveHeaders:
    login:
      path: /login
      url: https://localhost:8080/
    oath:
      path: /oauth/**
      url: https://localhost:8080/oauth
      # needed for all headers to be forwarded both in request & response
      sensitiveHeaders:
      # needed for self-signed certificates to work
  ssl-hostname-validation-enabled: false
  # fix the url returned inside HATEOAS links (otherwise it's: ..../api/api/....)
  add-proxy-headers: false
logging:
  level:
    org:
      springframework: debug
